command_timeout = 1000

[aws]
symbol = "îŒ½  aws"

[buf]
symbol = "ï’ buf"

[c]
symbol = "î˜ conda"

[conda]
symbol = "ï„Œ dart"

[dart]
symbol = "î˜ dart"

[directory]
read_only = "ï ½ dir"

[docker_context]
symbol = "ïŒˆ docker_context"

[elixir]
symbol = "î‰µ elixir"

[elm]
symbol = "î˜¬ elm"

[fossil_branch]
symbol = "ï˜ fossil_branch "

[git_branch]
symbol = "ï˜ git_branch "

[golang]
symbol = "î˜§ golang"

[guix_shell]
symbol = "ïŒ¥ guix_shell"

[haskell]
symbol = "î· haskell"

[haxe]
symbol = "âŒ˜ haxe"

[hg_branch]
symbol = "ï˜ hg_branch "

[java]
symbol = "î‰– java"

[julia]
symbol = "î˜¤ julia"

[lua]
symbol = "î˜  lua"

[memory_usage]
symbol = "ï¡š mem_usage"

[meson]
symbol = "ï¨¶ meson"

[nim]
symbol = "ïš¤ nim"

[nix_shell]
symbol = "ïŒ“ nix_shell"

[nodejs]
symbol = "îœ˜ nodejs"

[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ï¯‘ "
Gentoo = "ïŒ "
HardenedBSD = "ï²Š "
Illumos = "ïœ· "
Linux = "ïŒš "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ïœ¹ "
openSUSE = "ïŒ” "
OracleLinux = "ï ¶ "
Pop = "îŠ£ "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ï”— "
Solus = "ï´± "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ï¡± "

[package]
symbol = "ï£– package"

[pijul_channel]
symbol = "ğŸªº pijul_channel"

[python]
symbol = "îˆµ rlang"

[rlang]
symbol = "ï³’ rlang"

[ruby]
symbol = "î‘ ruby"

[rust]
symbol = "î¨ rust"

[scala]
symbol = "îœ· scala"

[spack]
symbol = "ğŸ…¢ spack"
